apiVersion: nais.io/v1alpha1
kind: Alert
metadata:
  name: grunnlagsdata-alerts
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: '#team-b√∏mlo-alerts'
  alerts:
    - alert: grunnlagsdata-har-ingen-aktive-pods
      expr: up{app=~"grunnlagsdata",job="kubernetes-pods"} == 0
      for: 2m
      description: grunnlagsdata mangler aktive pods i produksjon!
      action: Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events,
        og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger
      sla: respond within 1h, during office hours
      severity: danger
